# Generated by Django 5.1.2 on 2024-11-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog_category_alter_blog_author_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='description',
        ),
    ]
