# Generated by Django 5.1.2 on 2025-01-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('correct_count', models.IntegerField(default=0)),
                ('exam_duration', models.IntegerField(default=10)),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.exam')),
            ],
        ),
    ]
